function m(b,a,c,d){b.m.ob(b.tb,a,c,d)}function n(b,a,c,d){b.m.ba?m(b,a,c,d):b.m.Pe()._OnMessageFromDOM({type:"event",component:b.tb,handler:a,dispatchOpts:d||null,data:c,responseId:null})}function q(b,a,c){b.m.B(b.tb,a,c)}function v(b,a){for(const [c,d]of a)q(b,c,d)}function w(b){b.Xb||(b.m.Ac(b.ee),b.Xb=!0)}window.La=class{constructor(b,a){this.m=b;this.tb=a;this.Xb=!1;this.ee=()=>this.Qa()}ld(){}Qa(){}};
window.Cf=class{constructor(){this.gd=-1}j(){-1!==this.gd&&(self.clearTimeout(this.gd),this.gd=-1)}};"use strict";function aa(b,a){q(b,"get-element",c=>{const d=x(b,c.elementId);return a(d,c)})}function x(b,a){b=b.Va.get(a);if(!b)throw Error(`no element with id ${a}`);return b.Vb}
window.pd=class extends self.La{constructor(b,a){super(b,a);this.Va=new Map;this.rb=!0;v(this,[["create",()=>{throw Error("required override");}],["destroy",c=>{c=c.elementId;const d=x(this,c);this.rb&&d.parentElement.removeChild(d);this.Va.delete(c)}],["set-visible",c=>{if(this.rb){var d=this.Va.get(c.elementId),e=d.Vb;d.Od?e.style.display=c.isVisible?"":"none":d.hf=!!c.isVisible}}],["update-position",c=>{if(this.rb){var d=this.Va.get(c.elementId),e=d.Vb,f=this.m;e.style.left=c.left+"px";e.style.top=
c.top+"px";e.style.width=c.width+"px";e.style.height=c.height+"px";var g=c.fontSize;null!==g&&(e.style.fontSize=g+"em");g=c.htmlIndex;d.nf=g;g=f.rd(g);g!==d.Ea&&(e.remove(),f.Lb(g).appendChild(e),d.Ea=g,f.Jc());c=c.htmlZIndex;c!==d.Rc&&(d.Rc=c,f.Jc());d.Od||(d.Od=!0,d.hf&&(e.style.display=""))}}],["update-state",c=>{x(this,c.elementId);throw Error("required override");}],["focus",c=>{const d=x(this,c.elementId);c.focus?d.focus():d.blur()}],["set-css-style",c=>{const d=x(this,c.elementId),e=c.prop;
c=c.val;e.startsWith("--")?d.style.setProperty(e,c):d.style[e]=c}],["set-attribute",c=>{x(this,c.elementId).setAttribute(c.name,c.val)}],["remove-attribute",c=>{x(this,c.elementId).removeAttribute(c.name)}]]);aa(this,c=>c)}};"use strict";const ba=/(iphone|ipod|ipad|macos|macintosh|mac os x)/i.test(navigator.userAgent),y=/android/i.test(navigator.userAgent),ca=/safari/i.test(navigator.userAgent)&&!/(chrome|chromium|edg\/|OPR\/|nwjs)/i.test(navigator.userAgent);let da=0;
function z(b){const a=document.createElement("script");a.async=!1;a.type="module";return b.sf?new Promise(c=>{const d="c3_resolve_"+da;++da;self[d]=c;a.textContent=b.wf+`\n\nself["${d}"]();`;document.head.appendChild(a)}):new Promise((c,d)=>{a.onload=c;a.onerror=d;a.src=b;document.head.appendChild(a)})}
async function ea(){if(!navigator.userActivation||"undefined"===typeof OffscreenCanvas)return!1;try{let b=!1;const a=new Worker(URL.createObjectURL(new Blob(['\n\tself.addEventListener("message", () =>\n\t{\n\t\ttry {\n\t\t\tconst offscreenCanvas = new OffscreenCanvas(32, 32);\n\t\t\tconst gl = offscreenCanvas.getContext("webgl");\n\t\t\tself.postMessage(!!gl);\n\t\t}\n\t\tcatch (err)\n\t\t{\n\t\t\tconsole.warn("Feature detection worker error:", err);\n\t\t\tself.postMessage(false);\n\t\t}\n\t});'],{type:"text/javascript"})),
{get type(){b=!0}}),c=await new Promise(d=>{a.addEventListener("message",e=>{a.terminate();d(e.data)});a.postMessage("")});return b&&c}catch(b){return console.warn("Error feature detecting worker mode: ",b),!1}}let A=new Audio;
const fa={"audio/webm; codecs=opus":!!A.canPlayType("audio/webm; codecs=opus"),"audio/ogg; codecs=opus":!!A.canPlayType("audio/ogg; codecs=opus"),"audio/webm; codecs=vorbis":!!A.canPlayType("audio/webm; codecs=vorbis"),"audio/ogg; codecs=vorbis":!!A.canPlayType("audio/ogg; codecs=vorbis"),"audio/mp4":!!A.canPlayType("audio/mp4"),"audio/mpeg":!!A.canPlayType("audio/mpeg")};A=null;async function ha(b){b=await ia(b);return(new TextDecoder("utf-8")).decode(b)}
function ia(b){return new Promise((a,c)=>{const d=new FileReader;d.onload=e=>a(e.target.result);d.onerror=e=>c(e);d.readAsArrayBuffer(b)})}const C=[];let D=0;window.RealFile=window.File;const F=[],G=new Map,H=new Map;let ja=0;const ka=[];self.runOnStartup=function(b){if("function"!==typeof b)throw Error("runOnStartup called without a function");ka.push(b)};const oa=new Set(["cordova","playable-ad","instant-games"]);let pa=!1;
window.Pa=class b{constructor(a){this.ba=a.yf;this.wa=null;this.aa="";this.cb=a.vf;this.Jb={};this.Xa=this.ta=null;this.Ua=[];this.ma=null;this.Sd=!0;this.M=[];this.ad=[];this.bd=!1;this.fe=()=>this.Ne();this.Tc=!1;this.Ld=0;this.yb=null;this.bb=-1;this.mf=()=>this.Ye();this.Gb=new Set;this.hd=null;this.ge=[];this.A=a.he;this.Yb="file"===location.protocol.substr(0,4);if("playable-ad"===this.A||"instant-games"===this.A)this.ba=!1;ca&&(this.ba=!1);if("cordova"===this.A&&this.ba&&y){const c=/Chrome\/(\d+)/i.exec(navigator.userAgent);
c&&90<=parseInt(c[1],10)||(this.ba=!1)}this.Na()?self.chrome.webview.addEventListener("message",c=>this.Ad(c.data)):"macos-wkwebview"===this.A&&(self.C3WrapperOnMessage=c=>this.Ad(c));this.ac=this.qa=null;"html5"!==this.A||window.isSecureContext||console.warn("[Construct] Warning: the browser indicates this is not a secure context. Some features may be unavailable. Use secure (HTTPS) hosting to ensure all features are available.");this.B("canvas","update-size",c=>this.bf(c));this.B("canvas","set-html-layer-count",
c=>this._OnSetHTMLLayerCount(c));this.B("canvas","cleanup-html-layers",()=>this.Te());this.B("runtime","cordova-fetch-local-file",c=>this.Ue(c));this.B("runtime","create-job-worker",()=>this.Ve());this.B("runtime","send-wrapper-extension-message",c=>this.af(c));"cordova"===this.A?document.addEventListener("deviceready",()=>this.Pb(a)):this.Pb(a)}j(){this.Bc();this.wa&&(this.wa=this.wa.onmessage=null);this.ta&&(this.ta.terminate(),this.ta=null);this.Xa&&(this.Xa.j(),this.Xa=null);for(const {canvas:a,
gb:c}of this.M)a.remove(),c.remove();this.M.length=0}ze(){return this.M[0].canvas}rd(a){return Math.min(a,this.M.length-1)}Lb(a){if(0>a||a>=this.M.length)throw new RangeError("invalid canvas layer");return this.M[a].gb}_GetHTMLWrapElement(a){return this.Lb(a)}De(){return ba&&"cordova"===this.A}mb(){const a=navigator.userAgent;return ba&&oa.has(this.A)||navigator.standalone||/crios\/|fxios\/|edgios\//i.test(a)}Be(){return y}sd(){return y&&oa.has(this.A)}ud(){return"windows-webview2"===this.A||!!("preview"===
this.A&&window.chrome&&window.chrome.webview&&window.chrome.webview.postMessage)}Na(){return this.ud()||"xbox-uwp-webview2"===this.A}async Pb(a){this.ba&&!await ea()&&(this.ba=!1);"macos-wkwebview"===this.A?this.pb({type:"ready"}):this.Na()&&(this.df(),this.ge=(await this.Se()).registeredComponentIds);if("playable-ad"===this.A){this.qa=self.c3_base64files;this.ac={};await this.Ke();for(let d=0,e=a.fb.length;d<e;++d){var c=a.fb[d];this.ac.hasOwnProperty(c)?a.fb[d]={sf:!0,wf:this.ac[c]}:this.qa.hasOwnProperty(c)&&
(a.fb[d]=URL.createObjectURL(this.qa[c]))}a.pc=[]}if("nwjs"===this.A&&self.nw&&self.nw.App.manifest["c3-steam-mode"]){let d=0;this.Ac(()=>{d++;document.documentElement.style.opacity=0===d%2?"1":"0.999"})}a.uf?this.aa=a.uf:(c=location.origin,this.aa=("null"===c?"file:///":c)+location.pathname,c=this.aa.lastIndexOf("/"),-1!==c&&(this.aa=this.aa.substr(0,c+1)));a.Af&&(this.Jb=a.Af);c=new MessageChannel;this.wa=c.port1;this.wa.onmessage=d=>this._OnMessageFromRuntime(d.data);window.c3_addPortMessageHandler&&
window.c3_addPortMessageHandler(d=>this.Xe(d));this.yb=new self.Ee(this);await qa(this.yb);"object"===typeof window.StatusBar&&window.StatusBar.hide();if("object"===typeof window.AndroidFullScreen)try{await new Promise((d,e)=>{window.AndroidFullScreen.immersiveMode(d,e)})}catch(d){console.error("Failed to enter Android immersive mode: ",d)}this.ba?await this.Re(a,c.port2):await this.Qe(a,c.port2)}Dc(a){a=this.Jb.hasOwnProperty(a)?this.Jb[a]:a.endsWith("/workermain.js")&&this.Jb.hasOwnProperty("workermain.js")?
this.Jb["workermain.js"]:"playable-ad"===this.A&&this.qa.hasOwnProperty(a)?this.qa[a]:a;a instanceof Blob&&(a=URL.createObjectURL(a));return a}async rc(a,c,d){if(a.startsWith("blob:"))return new Worker(a,d);if("cordova"===this.A&&this.Yb)return a=await this.Kb(d.rf?a:this.cb+a),new Worker(URL.createObjectURL(new Blob([a],{type:"application/javascript"})),d);a=new URL(a,c);if(location.origin!==a.origin){a=await fetch(a);if(!a.ok)throw Error("failed to fetch worker script");a=await a.blob();return new Worker(URL.createObjectURL(a),
d)}return new Worker(a,d)}oa(){return Math.max(window.innerWidth,1)}ga(){return Math.max(window.innerHeight,1)}tc(){return this.Na()||(new Set(["cordova","nwjs","macos-wkwebview"])).has(this.A)?"standalone":window.matchMedia("(display-mode: fullscreen)").matches?"fullscreen":window.matchMedia("(display-mode: standalone)").matches?"standalone":window.matchMedia("(display-mode: minimal-ui)").matches?"minimal-ui":navigator.standalone?"standalone":"browser"}yd(a){var c=this.aa,d=location.href,e=this.oa(),
f=this.ga(),g=this.tc(),h=window.devicePixelRatio,k=b.lb(),l=a.Ff,p=window.cr_previewImageBlobs||this.qa,r=window.cr_previewProjectFileBlobs,t=window.cr_previewProjectFiles,u=window.cr_swClientId||"";a=a.he;var Z=(new URLSearchParams(self.location.search)).has("debug"),E=this.yb;return{runtimeBaseUrl:c,previewUrl:d,windowInnerWidth:e,windowInnerHeight:f,cssDisplayMode:g,devicePixelRatio:h,isFullscreen:k,projectData:l,previewImageBlobs:p,previewProjectFileBlobs:r,previewProjectFileSWUrls:t,swClientId:u,
exportType:a,isDebug:Z,ife:!!self.Ef,jobScheduler:{inputPort:E.Sc,outputPort:E.$c,maxNumWorkers:E.jf},supportedAudioFormats:fa,opusWasmScriptUrl:window.cr_opusWasmScriptUrl||this.cb+"opus.wasm.js",opusWasmBinaryUrl:window.cr_opusWasmBinaryUrl||this.cb+"opus.wasm.wasm",isFileProtocol:this.Yb,isiOSCordova:this.De(),isiOSWebView:this.mb(),isWindowsWebView2:this.ud(),isAnyWebView2Wrapper:this.Na(),wrapperComponentIds:this.ge,isFBInstantAvailable:"undefined"!==typeof self.FBInstant}}async Re(a,c){const d=
this.Dc(a.zf);"preview"===this.A?(this.ta=new Worker("previewworker.js",{type:"module",name:"Runtime"}),await new Promise((l,p)=>{const r=t=>{this.ta.removeEventListener("message",r);t.data&&"ok"===t.data.type?l():p()};this.ta.addEventListener("message",r);this.ta.postMessage({type:"construct-worker-init","import":(new URL(d,this.aa)).toString()})})):this.ta=await this.rc(d,this.aa,{type:"module",name:"Runtime",rf:!0});const e=document.createElement("canvas");e.style.display="none";const f=e.transferControlToOffscreen();
document.body.appendChild(e);const g=document.createElement("div");g.className="c3htmlwrap";document.body.appendChild(g);this.M.push({canvas:e,gb:g});window.c3canvas=e;self.C3_InsertHTMLPlaceholders&&self.C3_InsertHTMLPlaceholders();let h=a.pc||[],k=a.fb;h=await Promise.all(h.map(l=>this.Ra(l)));k=await Promise.all(k.map(l=>this.Ra(l)));if("cordova"===this.A)for(let l=0,p=a.oc.length;l<p;++l){const r=a.oc[l],t=r[0];if(t===a.jd||"scriptsInEvents.js"===t||t.endsWith("/scriptsInEvents.js"))r[1]=await this.Ra(t)}this.ta.postMessage(Object.assign(this.yd(a),
{type:"init-runtime",isInWorker:!0,messagePort:c,canvas:f,workerDependencyScripts:h,engineScripts:k,projectScripts:a.oc,mainProjectScript:a.jd,projectScriptsStatus:self.C3_ProjectScriptsStatus}),[c,f,...ra(this.yb)]);this.Ua=F.map(l=>new l(this));this.xd();sa(e);ta(g);ua(this.ma);self.c3_callFunction=(l,p)=>{var r=this.ma;return r.m.vd(r.tb,"js-invoke-function",{name:l,params:p})};"preview"===this.A&&(self.goToLastErrorScript=()=>this.ob("runtime","go-to-last-error-script"))}async Qe(a,c){const d=
document.createElement("canvas");d.style.display="none";document.body.appendChild(d);var e=document.createElement("div");e.className="c3htmlwrap";document.body.appendChild(e);this.M.push({canvas:d,gb:e});window.c3canvas=d;self.C3_InsertHTMLPlaceholders&&self.C3_InsertHTMLPlaceholders();this.Ua=F.map(h=>new h(this));this.xd();sa(d);ta(e);e=a.fb.map(h=>"string"===typeof h?(new URL(h,this.aa)).toString():h);if(Array.isArray(a.pc)){var f=[...a.pc].map(h=>h instanceof Blob?URL.createObjectURL(h):h);e.unshift(...f)}e=
await Promise.all(e.map(h=>this.Ra(h)));await Promise.all(e.map(h=>z(h)));e=self.C3_ProjectScriptsStatus;f=a.jd;const g=a.oc;for(let [h,k]of g)if(k||(k=h),h===f)try{k=await this.Ra(k),await z(k),"preview"!==this.A||e[h]||this.Cd(h,"main script did not run to completion")}catch(l){this.Cd(h,l)}else if("scriptsInEvents.js"===h||h.endsWith("/scriptsInEvents.js"))k=await this.Ra(k),await z(k);"preview"===this.A&&"object"!==typeof self.Bf.Df?(this.Rb(),console.error("[C3 runtime] Failed to load JavaScript code used in events. Check all your JavaScript code has valid syntax."),
alert("Failed to load JavaScript code used in events. Check all your JavaScript code has valid syntax.")):(a=Object.assign(this.yd(a),{isInWorker:!1,messagePort:c,canvas:d,runOnStartupFunctions:ka}),ua(this.ma),this.zd(),this.Xa=self.C3_CreateRuntime(a),await self.C3_InitRuntime(this.Xa,a))}Cd(a,c){this.Rb();console.error(`[Preview] Failed to load project main script (${a}): `,c);alert(`Failed to load project main script (${a}). Check all your JavaScript code has valid syntax. Press F12 and check the console for error details.`)}zd(){this.Rb()}Rb(){const a=
window.cr_previewLoadingElem;a&&(a.parentElement.removeChild(a),window.cr_previewLoadingElem=null)}async Ve(){const a=await va(this.yb);return{outputPort:a,transferables:[a]}}bf(a){if(!this.Tc){var c=a.styleWidth+"px",d=a.styleHeight+"px",e=a.marginLeft+"px",f=a.marginTop+"px";for(const {canvas:g,gb:h}of this.M)g.style.width=c,g.style.height=d,g.style.marginLeft=e,g.style.marginTop=f,h.style.width=c,h.style.height=d,h.style.marginLeft=e,h.style.marginTop=f,this.Sd&&(g.style.display="",h.style.display=
"");document.documentElement.style.setProperty("--construct-scale",a.displayScale);this.Sd=!1}}_OnSetHTMLLayerCount(a){var c=a.count,d=a.immediate,e=a.styleWidth+"px",f=a.styleHeight+"px";const g=a.marginLeft+"px",h=a.marginTop+"px";a=[];const k=[];if(c<this.M.length)for(;this.M.length>c;){const {canvas:l,gb:p}=this.M.pop();p.remove();this.ba&&!d?this.ad.push(l):l.remove()}else if(c>this.M.length)for(let l=0,p=c-this.M.length;l<p;++l)c=document.createElement("canvas"),c.classList.add("c3overlay"),
this.ba?(d=c.transferControlToOffscreen(),a.push(d),k.push(d)):a.push(c),document.body.appendChild(c),d=document.createElement("div"),d.classList.add("c3htmlwrap","c3overlay"),document.body.appendChild(d),c.style.width=e,c.style.height=f,c.style.marginLeft=g,c.style.marginTop=h,d.style.width=e,d.style.height=f,d.style.marginLeft=g,d.style.marginTop=h,sa(c),ta(d),this.M.push({canvas:c,gb:d});for(const l of this.Ua)if(l instanceof window.pd&&l.rb)for(const p of l.Va.values())e=l.m.rd(p.nf),f=p.Ea,-1!==
e&&-1!==f&&e!==f&&(f=p.Vb,f.remove(),l.m.Lb(e).appendChild(f),p.Ea=e);this.Jc();return{addedCanvases:a,transferables:k}}Te(){for(const a of this.ad)a.remove();this.ad.length=0}Jc(){this.bd||(this.bd=!0,this.Ac(this.fe))}Ne(){this.Bd(this.fe);this.bd=!1;let a=[];for(var c of this.Ua)if(c instanceof window.pd){var d=c.rb?[...c.Va.values()]:null;d&&a.push(...d)}a.sort((g,h)=>{const k=g.Ea,l=h.Ea;return k!==l?k-l:g.Rc-h.Rc});let e=d=c=0,f=a.length;for(;e<f;++e){const g=a[e];g.Ea!==c&&(this.wd(c,a.slice(d,
e)),c=g.Ea,d=e)}d<e&&this.wd(c,a.slice(d,e))}wd(a,c){if(!(1>=c.length||a>=this.M.length)){c=c.map(k=>k.Vb);var d=new Set(c);a=this.Lb(a);for(var e=Array.from(a.children).filter(k=>d.has(k)),f=0,g=Math.min(c.length,e.length);f<g&&c[f]===e[f];++f);for(var h=f;h<g;++h)e[h].remove();for(h=f;h<g;++h)a.appendChild(c[h])}}Pe(){if(this.ba)throw Error("not available in worker mode");return this.Xa}ob(a,c,d,e,f){this.wa.postMessage({type:"event",component:a,handler:c,dispatchOpts:e||null,data:d,responseId:null},
f)}vd(a,c,d,e,f){const g=ja++,h=new Promise((k,l)=>{H.set(g,{resolve:k,reject:l})});this.wa.postMessage({type:"event",component:a,handler:c,dispatchOpts:e||null,data:d,responseId:g},f);return h}_OnMessageFromRuntime(a){const c=a.type;if("event"===c)return this.We(a);if("result"===c)this.Ze(a);else if("runtime-ready"===c)this.$e();else if("alert-error"===c)this.Rb(),alert(a.message);else if("creating-runtime"===c)this.zd();else throw Error(`unknown message '${c}'`);}We(a){const c=a.component,d=a.handler,
e=a.data,f=a.responseId;if(a=G.get(c))if(a=a.get(d)){var g=null;try{g=a(e)}catch(h){console.error(`Exception in '${c}' handler '${d}':`,h);null!==f&&this.Qb(f,!1,""+h);return}if(null===f)return g;g&&g.then?g.then(h=>this.Qb(f,!0,h)).catch(h=>{console.error(`Rejection from '${c}' handler '${d}':`,h);this.Qb(f,!1,""+h)}):this.Qb(f,!0,g)}else console.warn(`[DOM] No handler '${d}' for component '${c}'`);else console.warn(`[DOM] No event handlers for component '${c}'`)}Qb(a,c,d){let e;d&&d.transferables&&
(e=d.transferables);this.wa.postMessage({type:"result",responseId:a,isOk:c,result:d},e)}Ze(a){const c=a.responseId,d=a.isOk;a=a.result;const e=H.get(c);d?e.resolve(a):e.reject(a);H.delete(c)}B(a,c,d){let e=G.get(a);e||(e=new Map,G.set(a,e));if(e.has(c))throw Error(`[DOM] Component '${a}' already has handler '${c}'`);e.set(c,d)}static hb(a){if(F.includes(a))throw Error("DOM handler already added");F.push(a)}xd(){for(const a of this.Ua)if("runtime"===a.tb){this.ma=a;return}throw Error("cannot find runtime DOM handler");
}Xe(a){this.ob("debugger","message",a)}$e(){for(const a of this.Ua)a.ld()}static lb(){return!!(document.fullscreenElement||document.webkitFullscreenElement||document.mozFullScreenElement||pa)}static Dd(a){pa=!!a}Ac(a){this.Gb.add(a);this.Ic()}Bd(a){this.Gb.delete(a);0===this.Gb.size&&this.Bc()}Ic(){-1===this.bb&&0<this.Gb.size&&(this.bb=requestAnimationFrame(this.mf))}Bc(){-1!==this.bb&&(cancelAnimationFrame(this.bb),this.bb=-1)}Ye(){this.bb=-1;for(const a of this.Gb)a();this.Ic()}Ca(a){this.ma.Ca(a)}Oa(a){this.ma.Oa(a)}Hc(){this.ma.Hc()}Ob(a){this.ma.Ob(a)}Ce(){return!!fa["audio/webm; codecs=opus"]}async ef(a){a=
await this.vd("runtime","opus-decode",{arrayBuffer:a},null,[a]);return new Float32Array(a)}Ge(a){this.Tc=!0;this.Ld=a}Ae(a){return/^(?:[a-z\-]+:)?\/\//.test(a)||"data:"===a.substr(0,5)||"blob:"===a.substr(0,5)}td(a){return!this.Ae(a)}async Ra(a){return"cordova"===this.A&&(a.startsWith("file:")||this.Yb&&this.td(a))?(a.startsWith(this.aa)&&(a=a.substr(this.aa.length)),a=await this.Kb(a),URL.createObjectURL(new Blob([a],{type:"application/javascript"}))):a}async Ue(a){const c=a.filename;switch(a.as){case "text":return await this.ye(c);
case "buffer":return await this.Kb(c);default:throw Error("unsupported type");}}od(a){const c=window.cordova.file.applicationDirectory+"www/"+a;return new Promise((d,e)=>{window.resolveLocalFileSystemURL(c,f=>{f.file(d,e)},e)})}async ye(a){a=await this.od(a);return await ha(a)}Cc(){if(C.length&&!(8<=D)){D++;var a=C.shift();this.Le(a.filename,a.xf,a.qf)}}Kb(a){return new Promise((c,d)=>{C.push({filename:a,xf:e=>{D--;this.Cc();c(e)},qf:e=>{D--;this.Cc();d(e)}});this.Cc()})}async Le(a,c,d){try{const e=
await this.od(a),f=await ia(e);c(f)}catch(e){d(e)}}Ad(a){if("entered-fullscreen"===a)b.Dd(!0),I(this.ma);else if("exited-fullscreen"===a)b.Dd(!1),I(this.ma);else if("object"===typeof a){const c=a.type;"directory-handles"!==c&&("wrapper-init-response"===c?(this.hd(a),this.hd=null):"extension-message"===c?this.ob("runtime","wrapper-extension-message",a):console.warn("Unknown wrapper message: ",a))}else console.warn("Unknown wrapper message: ",a)}af(a){this.pb({type:"extension-message",componentId:a.componentId,
messageId:a.messageId,params:a.params||[],asyncId:a.asyncId})}pb(a){this.Na()?window.chrome.webview.postMessage(JSON.stringify(a)):"macos-wkwebview"===this.A&&window.webkit.messageHandlers.C3Wrapper.postMessage(JSON.stringify(a))}df(){window.moveTo=(a,c)=>{this.pb({type:"set-window-position",windowX:Math.ceil(a),windowY:Math.ceil(c)})};window.resizeTo=(a,c)=>{this.pb({type:"set-window-size",windowWidth:Math.ceil(a),windowHeight:Math.ceil(c)})}}Se(){return this.Na()?new Promise(a=>{this.hd=a;this.pb({type:"wrapper-init"})}):
Promise.resolve()}async Ke(){const a=[];for(const [c,d]of Object.entries(this.qa))a.push(this.Je(c,d));await Promise.all(a)}async Je(a,c){if("object"===typeof c)this.qa[a]=new Blob([c.str],{type:c.type}),this.ac[a]=c.str;else{let d=await this.Oe(c);d||(d=this.Me(c));this.qa[a]=d}}async Oe(a){try{return await (await fetch(a)).blob()}catch(c){return console.warn("Failed to fetch a data: URI. Falling back to a slower workaround. This is probably because the Content Security Policy unnecessarily blocked it. Allow data: URIs in your CSP to avoid this.",
c),null}}Me(a){a=this.cf(a);return this.Ie(a.data,a.tf)}cf(a){var c=a.indexOf(",");if(0>c)throw new URIError("expected comma in data: uri");var d=a.substring(c+1);c=a.substring(5,c).split(";");a=c[0]||"";const e=c[2];d="base64"===c[1]||"base64"===e?atob(d):decodeURIComponent(d);return{tf:a,data:d}}Ie(a,c){var d=a.length;let e=d>>2,f=new Uint8Array(d),g=new Uint32Array(f.buffer,0,e),h,k;for(k=h=0;h<e;++h)g[h]=a.charCodeAt(k++)|a.charCodeAt(k++)<<8|a.charCodeAt(k++)<<16|a.charCodeAt(k++)<<24;for(d&=
3;d--;)f[k]=a.charCodeAt(k),++k;return new Blob([f],{type:c})}};"use strict";const J=self.Pa,wa=new Map([["OSLeft","MetaLeft"],["OSRight","MetaRight"]]),K={dispatchRuntimeEvent:!0,dispatchUserScriptEvent:!0},xa={dispatchUserScriptEvent:!0},ya={dispatchRuntimeEvent:!0};function za(b){return new Promise((a,c)=>{const d=document.createElement("link");d.onload=()=>a(d);d.onerror=e=>c(e);d.rel="stylesheet";d.href=b;document.head.appendChild(d)})}
function Aa(b){return new Promise((a,c)=>{const d=new Image;d.onload=()=>a(d);d.onerror=e=>c(e);d.src=b})}async function Ba(b){b=URL.createObjectURL(b);try{return await Aa(b)}finally{URL.revokeObjectURL(b)}}function Ca(b){do{if(b.parentNode&&b.hasAttribute("contenteditable"))return!0;b=b.parentNode}while(b);return!1}const Da=new Set(["input","textarea","datalist","select"]),Ea=new Set(["canvas","body","html"]);
function L(b){b.target.tagName&&Ea.has(b.target.tagName.toLowerCase())&&b.preventDefault()}function Fa(b){b.target.tagName&&b.target.classList.contains("c3htmlwrap")&&b.preventDefault()}function Ga(b){(b.metaKey||b.ctrlKey)&&b.preventDefault()}
self.C3_GetSvgImageSize=async function(b){b=await Ba(b);if(0<b.width&&0<b.height)return[b.width,b.height];b.style.position="absolute";b.style.left="0px";b.style.top="0px";b.style.visibility="hidden";document.body.appendChild(b);const a=b.getBoundingClientRect();document.body.removeChild(b);return[a.width,a.height]};self.C3_RasterSvgImageBlob=async function(b,a,c,d,e){b=await Ba(b);const f=document.createElement("canvas");f.width=d;f.height=e;f.getContext("2d").drawImage(b,0,0,a,c);return f};
let Ha=!1;document.addEventListener("pause",()=>Ha=!0);document.addEventListener("resume",()=>Ha=!1);function sa(b){b.addEventListener("selectstart",L);b.addEventListener("gesturehold",L);b.addEventListener("pointerdown",L)}function ta(b){b.addEventListener("selectstart",Fa);b.addEventListener("gesturehold",Fa);b.addEventListener("touchstart",Fa)}function ua(b){b.Kd=!0;b.Wc=b.m.oa();b.zb=b.m.ga()}
function I(b){if(!b.ka){var a=J.lb();a&&"any"!==b.ed&&Ia(b);m(b,"fullscreenchange",{isFullscreen:a,innerWidth:b.oa(),innerHeight:b.ga()})}}async function Ja(b){await Promise.all(b.webfonts.map(async a=>{a=new FontFace(a.name,`url('${a.url}')`);document.fonts.add(a);await a.load()}))}
async function Ka(b){var a=b.imageBitmapOpts;b=await self.C3_RasterSvgImageBlob(b.blob,b.imageWidth,b.imageHeight,b.surfaceWidth,b.surfaceHeight);a=a?await createImageBitmap(b,a):await createImageBitmap(b);return{imageBitmap:a,transferables:[a]}}async function Ma(b){return await self.C3_GetSvgImageSize(b.blob)}function Na(b){window.c3_postToMessagePort&&(b.from="runtime",window.c3_postToMessagePort(b))}
function Oa(b){self.setTimeout(()=>{b.Jd=!0},1E3);"cordova"===b.m.A?(document.addEventListener("pause",()=>Qa(b,!0)),document.addEventListener("resume",()=>Qa(b,!1))):document.addEventListener("visibilitychange",()=>Qa(b,"hidden"===document.visibilityState));b.ec=!("hidden"!==document.visibilityState&&!Ha);return{isSuspended:b.ec}}
function Ra(b){b.Fd||(b.Fd=!0,window.addEventListener("deviceorientation",a=>{b.ka||m(b,"deviceorientation",{absolute:!!a.absolute,alpha:a.alpha||0,beta:a.beta||0,gamma:a.gamma||0,timeStamp:a.timeStamp,webkitCompassHeading:a.webkitCompassHeading,webkitCompassAccuracy:a.webkitCompassAccuracy},K)}),window.addEventListener("deviceorientationabsolute",a=>{b.ka||m(b,"deviceorientationabsolute",{absolute:!!a.absolute,alpha:a.alpha||0,beta:a.beta||0,gamma:a.gamma||0,timeStamp:a.timeStamp},K)}))}
function Sa(b){b.Ed||(b.Ed=!0,window.addEventListener("devicemotion",a=>{if(!b.ka){var c=null,d=a.acceleration;d&&(c={x:d.x||0,y:d.y||0,z:d.z||0});d=null;var e=a.accelerationIncludingGravity;e&&(d={x:e.x||0,y:e.y||0,z:e.z||0});e=null;var f=a.rotationRate;f&&(e={alpha:f.alpha||0,beta:f.beta||0,gamma:f.gamma||0});m(b,"devicemotion",{acceleration:c,accelerationIncludingGravity:d,rotationRate:e,interval:a.interval,timeStamp:a.timeStamp},K)}}))}async function Ta(b){await za(b.url)}
function Ua(b,a){b.Md=a.message;-1===b.Nc&&(b.Nc=setTimeout(()=>{b.Nc=-1;const c=document.getElementById("exportToVideoMessage");c&&(c.textContent=b.Md)},250))}function Va(b,a){console.warn("[Construct] Fullscreen request failed: ",a);m(b,"fullscreenerror",{isFullscreen:J.lb(),innerWidth:b.oa(),innerHeight:b.ga()})}
function Qa(b,a){b.ec!==a&&((b.ec=a)?b.m.Bc():b.m.Ic(),m(b,"visibilitychange",{hidden:a}),!a&&b.m.mb()&&(b=()=>{document.scrollingElement.scrollTop=0;document.scrollingElement.scrollLeft=0},setTimeout(b,50),setTimeout(b,100),setTimeout(b,250),setTimeout(b,500)))}
function Wa(b,a,c){"Backspace"===c.key&&L(c);"nwjs"===b.m.A&&"u"===c.key&&(c.ctrlKey||c.metaKey)&&c.preventDefault();if(!b.ka){var d=wa.get(c.code)||c.code;n(b,a,{code:d,key:c.key,which:c.which,repeat:c.repeat,altKey:c.altKey,ctrlKey:c.ctrlKey,metaKey:c.metaKey,shiftKey:c.shiftKey,timeStamp:c.timeStamp},K)}}
function M(b,a,c,d){b.ka||c.sourceCapabilities&&c.sourceCapabilities.firesTouchEvents||c.originalEvent&&c.originalEvent.sourceCapabilities&&c.originalEvent.sourceCapabilities.firesTouchEvents||n(b,a,{button:c.button,buttons:c.buttons,clientX:c.clientX,clientY:c.clientY+b.za,pageX:c.pageX,pageY:c.pageY+b.za,movementX:c.movementX||0,movementY:c.movementY||0,timeStamp:c.timeStamp},d)}
function N(b,a,c){if(!b.ka){var d=0;"mouse"===c.pointerType&&(d=b.Yc);n(b,a,{pointerId:c.pointerId,pointerType:c.pointerType,button:c.button,buttons:c.buttons,lastButtons:d,clientX:c.clientX,clientY:c.clientY+b.za,pageX:c.pageX,pageY:c.pageY+b.za,movementX:c.movementX||0,movementY:c.movementY||0,width:c.width||0,height:c.height||0,pressure:c.pressure||0,tangentialPressure:c.tangentialPressure||0,tiltX:c.tiltX||0,tiltY:c.tiltY||0,twist:c.twist||0,timeStamp:c.timeStamp},K);"mouse"===c.pointerType&&
(b.Yc=c.buttons)}}function Xa(b,a,c){document.body.style.position="";document.body.style.overflow="";document.body.style.transform="";b.za=0;if(0<c){var d=document.activeElement;d&&(d=d.getBoundingClientRect(),a=(d.top+d.bottom)/2-(a-c)/2,a>c&&(a=c),0>a&&(a=0),0<a&&(document.body.style.position="absolute",document.body.style.overflow="visible",document.body.style.transform=`translateY(${-a}px)`,b.za=a))}}
function Ya(b,a,c,d){const e=b.oa(),f=b.ga();b.eb=-1;e!=a||f!=c?m(b,"window-resize",{innerWidth:e,innerHeight:f,devicePixelRatio:window.devicePixelRatio,isFullscreen:J.lb(),cssDisplayMode:b.m.tc()}):10>d&&Za(b,e,f,d+1)}function Za(b,a,c,d){-1!==b.eb&&clearTimeout(b.eb);b.eb=setTimeout(()=>Ya(b,a,c,d),48)}
function Ia(b){b=b.ed;if(screen.orientation&&screen.orientation.lock)screen.orientation.lock(b).catch(a=>console.warn("[Construct] Failed to lock orientation: ",a));else try{let a=!1;screen.lockOrientation?a=screen.lockOrientation(b):screen.webkitLockOrientation?a=screen.webkitLockOrientation(b):screen.mozLockOrientation?a=screen.mozLockOrientation(b):screen.msLockOrientation&&(a=screen.msLockOrientation(b));a||console.warn("[Construct] Failed to lock orientation")}catch(a){console.warn("[Construct] Failed to lock orientation: ",
a)}}function $a(b){return!b||b===document||b===window||b===document.body||"canvas"===b.tagName.toLowerCase()}
J.hb(class extends self.La{constructor(b){super(b,"runtime");this.Kd=!1;this.eb=-1;this.ed="any";this.ec=this.Ed=this.Fd=!1;this.lc=document.createElement("div");this.lc.className="c3-screen-reader-text";this.lc.setAttribute("aria-live","polite");document.body.appendChild(this.lc);this.Ga=null;this.ka=!1;this.Md="";this.Nc=-1;this.Jd=!1;this.Wc=b.oa();this.zb=b.ga();this.za=this.Ib=0;b.B("runtime","invoke-download",c=>{const d=c.url;c=c.filename;const e=document.createElement("a"),f=document.body;
e.textContent=c;e.href=d;e.download=c;f.appendChild(e);e.click();f.removeChild(e)});b.B("runtime","load-webfonts",c=>Ja(c));b.B("runtime","raster-svg-image",c=>Ka(c));b.B("runtime","get-svg-image-size",c=>Ma(c));b.B("runtime","set-target-orientation",c=>{this.ed=c.targetOrientation});b.B("runtime","register-sw",()=>{window.C3_RegisterSW&&window.C3_RegisterSW()});b.B("runtime","post-to-debugger",c=>Na(c));b.B("runtime","go-to-script",c=>Na(c));b.B("runtime","before-start-ticking",()=>Oa(this));b.B("runtime",
"debug-highlight",c=>{if(c.show){this.Ga||(this.Ga=document.createElement("div"),this.Ga.id="inspectOutline",document.body.appendChild(this.Ga));var d=this.Ga;d.style.display="";d.style.left=c.left-1+"px";d.style.top=c.top-1+"px";d.style.width=c.width+2+"px";d.style.height=c.height+2+"px";d.textContent=c.name}else this.Ga&&(this.Ga.style.display="none")});b.B("runtime","enable-device-orientation",()=>Ra(this));b.B("runtime","enable-device-motion",()=>Sa(this));b.B("runtime","add-stylesheet",c=>Ta(c));
b.B("runtime","script-create-worker",c=>{const d=c.port2;(new Worker(c.url,c.opts)).postMessage({type:"construct-worker-init",port2:d},[d])});b.B("runtime","alert",c=>{alert(c.message)});b.B("runtime","screen-reader-text",c=>{var d=c.type;"create"===d?(d=document.createElement("p"),d.id="c3-sr-"+c.id,d.textContent=c.text,this.lc.appendChild(d)):"update"===d?(d=document.getElementById("c3-sr-"+c.id))?d.textContent=c.text:console.warn(`[Construct] Missing screen reader text with id ${c.id}`):"release"===
d?(d=document.getElementById("c3-sr-"+c.id))?d.remove():console.warn(`[Construct] Missing screen reader text with id ${c.id}`):console.warn(`[Construct] Unknown screen reader text update '${d}'`)});b.B("runtime","hide-cordova-splash",()=>{navigator.splashscreen&&navigator.splashscreen.hide&&navigator.splashscreen.hide()});b.B("runtime","set-exporting-to-video",c=>{this.ka=!0;const d=document.createElement("h1");d.id="exportToVideoMessage";d.textContent=c.message;document.body.prepend(d);document.body.classList.add("exportingToVideo");
this.m.ze().style.display="";this.m.Ge(c.duration)});b.B("runtime","export-to-video-progress",c=>Ua(this,c));b.B("runtime","exported-to-video",c=>{window.pf({type:"exported-video",arrayBuffer:c.arrayBuffer,contentType:c.contentType,time:c.time})});b.B("runtime","exported-to-image-sequence",c=>{window.pf({type:"exported-image-sequence",blobArr:c.blobArr,time:c.time,gif:c.gif})});const a=new Set(["input","textarea","datalist"]);window.addEventListener("contextmenu",c=>{const d=c.target;a.has(d.tagName.toLowerCase())||
Ca(d)||c.preventDefault()});window.addEventListener("selectstart",L);window.addEventListener("gesturehold",L);window.addEventListener("touchstart",L,{passive:!1});window.addEventListener("pointerdown",L,{passive:!1});this.Yc=0;window.addEventListener("mousedown",c=>{1===c.button&&c.preventDefault()});window.addEventListener("mousewheel",Ga,{passive:!1});window.addEventListener("wheel",Ga,{passive:!1});window.addEventListener("resize",()=>{a:{if(!this.ka&&this.Kd){var c=this.oa();var d=this.ga();if(this.m.sd()){if(this.Jd){if(this.Wc===
c&&d<this.zb){this.Ib=this.zb-d;Xa(this,this.zb,this.Ib);c=void 0;break a}0<this.Ib&&(this.Ib=0,Xa(this,d,this.Ib))}this.Wc=c;this.zb=d}m(this,"window-resize",{innerWidth:c,innerHeight:d,devicePixelRatio:window.devicePixelRatio,isFullscreen:J.lb(),cssDisplayMode:this.m.tc()});this.m.mb()&&(-1!==this.eb&&clearTimeout(this.eb),Ya(this,c,d,0))}c=void 0}return c});window.addEventListener("fullscreenchange",()=>I(this));window.addEventListener("webkitfullscreenchange",()=>I(this));window.addEventListener("mozfullscreenchange",
()=>I(this));window.addEventListener("fullscreenerror",c=>Va(this,c));window.addEventListener("webkitfullscreenerror",c=>Va(this,c));window.addEventListener("mozfullscreenerror",c=>Va(this,c));if(b.mb()){let c=Infinity;window.visualViewport.addEventListener("resize",()=>{const d=window.visualViewport.height;d>c&&(document.scrollingElement.scrollTop=0,document.scrollingElement.scrollLeft=0);c=d});document.documentElement.setAttribute("ioswebview","")}this.Ya=new Set;this.cc=new WeakSet;this.va=!1}ld(){window.addEventListener("focus",
()=>{m(this,"window-focus",null,ya)});window.addEventListener("blur",()=>{try{var a=window.parent&&window.parent.document.hasFocus()}catch(c){a=!1}m(this,"window-blur",{parentHasFocus:a},ya);this.Yc=0});window.addEventListener("focusin",a=>{a=a.target;(Da.has(a.tagName.toLowerCase())||Ca(a))&&m(this,"keyboard-blur",null,ya)});window.addEventListener("keydown",a=>Wa(this,"keydown",a));window.addEventListener("keyup",a=>Wa(this,"keyup",a));window.addEventListener("mousedown",a=>M(this,"mousedown",a,
xa));window.addEventListener("mousemove",a=>M(this,"mousemove",a,xa));window.addEventListener("mouseup",a=>M(this,"mouseup",a,xa));window.addEventListener("dblclick",a=>M(this,"dblclick",a,K));window.addEventListener("wheel",a=>{this.ka||m(this,"wheel",{clientX:a.clientX,clientY:a.clientY+this.za,pageX:a.pageX,pageY:a.pageY+this.za,deltaX:a.deltaX,deltaY:a.deltaY,deltaZ:a.deltaZ,deltaMode:a.deltaMode,timeStamp:a.timeStamp},K)});window.addEventListener("pointerdown",a=>{window!==window.top&&window.focus();
$a(a.target)&&document.activeElement&&!$a(document.activeElement)&&document.activeElement.blur();N(this,"pointerdown",a)});this.m.ba&&"undefined"!==typeof window.onpointerrawupdate&&self===self.top?window.addEventListener("pointerrawupdate",a=>{N(this,"pointermove",a)}):window.addEventListener("pointermove",a=>N(this,"pointermove",a));window.addEventListener("pointerup",a=>N(this,"pointerup",a));window.addEventListener("pointercancel",a=>N(this,"pointercancel",a));const b=()=>this.Hc();window.addEventListener("pointerup",
b,!0);window.addEventListener("touchend",b,!0);window.addEventListener("click",b,!0);window.addEventListener("keydown",b,!0);window.addEventListener("gamepadconnected",b,!0);this.m.Be()&&!this.m.sd()&&navigator.virtualKeyboard&&(navigator.virtualKeyboard.overlaysContent=!0,navigator.virtualKeyboard.addEventListener("geometrychange",()=>{Xa(this,this.ga(),navigator.virtualKeyboard.boundingRect.height)}));this.m.mb()&&(document.scrollingElement.scrollTop=0,document.scrollingElement.scrollLeft=0)}oa(){return this.m.oa()}ga(){return this.m.ga()}Hc(){var b=
[...this.Ya];this.Ya.clear();if(!this.va)for(const a of b)(b=a.play())&&b.catch(()=>{this.cc.has(a)||this.Ya.add(a)})}Ca(b){if("function"!==typeof b.play)throw Error("missing play function");this.cc.delete(b);let a;try{a=b.play()}catch(c){this.Ya.add(b);return}a&&a.catch(()=>{this.cc.has(b)||this.Ya.add(b)})}Oa(b){this.Ya.delete(b);this.cc.add(b)}Ob(b){this.va=!!b}});"use strict";
async function qa(b){if(b.ff)throw Error("already initialised");b.ff=!0;var a=b.xa.Dc(("playable-ad"===b.xa.A?b.xa.cb:"")+"dispatchworker.js");b.Mc=await b.xa.rc(a,b.sb,{name:"DispatchWorker"});a=new MessageChannel;b.Sc=a.port1;b.Mc.postMessage({type:"_init","in-port":a.port2},[a.port2]);b.$c=await va(b)}function ra(b){return[b.Sc,b.$c]}
async function va(b){const a=b.Td.length;var c=b.xa.Dc(("playable-ad"===b.xa.A?b.xa.cb:"")+"jobworker.js");c=await b.xa.rc(c,b.sb,{name:"JobWorker"+a});const d=new MessageChannel,e=new MessageChannel;b.Mc.postMessage({type:"_addJobWorker",port:d.port1},[d.port1]);c.postMessage({type:"init",number:a,"dispatch-port":d.port2,"output-port":e.port2},[d.port2,e.port2]);b.Td.push(c);return e.port1}
self.Ee=class{constructor(b){this.xa=b;this.sb=b.aa;this.sb="preview"===b.A?this.sb+"workers/":this.sb+b.cb;this.jf=Math.min(navigator.hardwareConcurrency||2,16);this.Mc=null;this.Td=[];this.$c=this.Sc=null}};"use strict";window.C3_Is_Supported&&(window.c3_runtimeInterface=new self.Pa({yf:!1,zf:"workermain.js",fb:["scripts/c3runtime.js"],oc:[],jd:"",vf:"scripts/",pc:[],he:"html5"}));"use strict";const ab=180/Math.PI;
async function bb(b,a){a.usePlayMusicAsSoundWorkaround&&(b.hc=!0);b.fd=a.timeScaleMode;b.Yd=["equalpower","HRTF","soundfield"][a.panningModel];b.Id=["linear","inverse","exponential"][a.distanceModel];b.Zd=a.refDistance;b.Xd=a.maxDistance;b.ae=a.rolloffFactor;if(b.m.Tc)b.hc=!0,b.g=new OfflineAudioContext({numberOfChannels:2,sampleRate:48E3,length:Math.ceil(48E3*b.m.Ld)});else{var c={latencyHint:a.latencyHint};b.de||(c.sampleRate=48E3);if("undefined"!==typeof AudioContext)b.g=new AudioContext(c);else if("undefined"!==
typeof webkitAudioContext)b.g=new webkitAudioContext(c);else throw Error("Web Audio API not supported");cb(b);b.g.onstatechange=()=>{"running"!==b.g.state&&cb(b);m(b,"audiocontext-state",{audioContextState:b.g.state})}}b.Ta=b.g.createGain();b.Ta.connect(b.g.destination);c=a.listenerPos;b.$[0]=c[0];b.$[1]=c[1];b.$[2]=c[2];b.g.listener.setPosition(c[0],c[1],c[2]);b.g.listener.setOrientation(...b.ca);self.C3_GetAudioContextCurrentTime=()=>b.g.currentTime;try{await Promise.all(a.preloadList.map(d=>O(b,
d.originalUrl,d.url,d.type,!1)))}catch(d){console.error("[Construct] Preloading sounds failed: ",d)}return{sampleRate:b.g.sampleRate,audioContextState:b.g.state,outputLatency:b.g.outputLatency||0}}
async function db(b,a){var c=a.originalUrl,d=a.url;const e=a.type,f=a.isMusic,g=a.tags,h=a.isLooping,k=a.vol,l=a.pos,p=a.panning,r=a.stereoPan;let t=a.off;0<t&&!a.trueClock&&(b.g.getOutputTimestamp?(a=b.g.getOutputTimestamp(),t=t-a.performanceTime/1E3+a.contextTime):t=t-performance.now()/1E3+b.g.currentTime);b.Ud=g.slice(0);eb(b,g);try{b.R=await fb(b,c,d,e,g,f);if(p){P(b.R,!0);var u=b.R,Z=p.x,E=p.y,vb=p.z,wb=p.angle,la=p.innerAngle,ma=p.outerAngle,na=p.outerGain;if(u.xb){gb(u,Z,E,vb,wb);var B=self.ib.He;
u.ra[0]!==B(la)&&(u.ra[0]=B(la),u.F.coneInnerAngle=B(la));u.ra[1]!==B(ma)&&(u.ra[1]=B(ma),u.F.coneOuterAngle=B(ma));u.ra[2]!==na&&(u.ra[2]=na,u.F.coneOuterGain=na)}p.hasOwnProperty("uid")&&(b.R.pa=p.uid)}else"number"===typeof r&&0!==r?(Q(b.R,!0),hb(b.R,r)):(P(b.R,!1),Q(b.R,!1));b.R.Play(h,k,l,t)}catch(xb){console.error("[Construct] Audio: error starting playback: ",xb);return}finally{c=g.join(" ");d=b.Fb.get(c);if(!d)throw Error("expected pending tag");d.kd--;0===d.kd&&(d.resolve(),b.Fb.delete(c))}w(b)}
async function jb(b,a){var c=a.tags;const d=a.vol,e=a.duration;a=a.stopOnEnd;await kb(b,c);for(const h of R(b,c))if(!h.ua){c=h.G.gain;c.cancelScheduledValues(0);var f=h.u.g.currentTime,g=f+e;c.setValueAtTime(c.value,f);c.linearRampToValueAtTime(d,g);h.Ka=d;h.Wa=g;h.ce=a}S(b)}async function lb(b,a){const c=a.tags;a=a.rate;await kb(b,c);for(const d of R(b,c))d.la!==a&&(d.la=a,d.Da())}async function mb(b,a){const c=a.tags;a=a.pos;await kb(b,c);for(const d of R(b,c))d.xc(a)}
async function nb(b,a){const c=a.originalUrl,d=a.url,e=a.type;a=a.isMusic;try{await fb(b,c,d,e,"",a)}catch(f){console.error("[Construct] Audio: error preloading: ",f)}}async function ob(b,a){if(a=await O(b,"",a.url,a.type,a.isMusic,!0))a.j(),a=b.ia.indexOf(a),-1!==a&&b.ia.splice(a,1)}
async function pb(b,a){const c=a.type;var d=a.hasOwnProperty("tags")?a.tags:[a.tag];const e=a.params;let f;if("convolution"===c)try{f=await O(b,a.bufferOriginalUrl,a.bufferUrl,a.bufferType,!1)}catch(k){console.log("[Construct] Audio: error loading convolution: ",k);return}for(const k of d){if("filter"===c)d=new self.ne(b,...e);else if("delay"===c)d=new self.le(b,...e);else if("convolution"===c){var g=d=new self.ke(b,f.ha,...e),h=a.bufferType;g.Gd=a.bufferOriginalUrl;g.Hd=h}else if("flanger"===c)d=
new self.oe(b,...e);else if("phaser"===c)d=new self.qe(b,...e);else if("gain"===c)d=new self.pe(b,...e);else if("stereopan"===c)d=new self.se(b,...e);else if("tremolo"===c)d=new self.te(b,...e);else if("ringmod"===c)d=new self.re(b,...e);else if("distortion"===c)d=new self.me(b,...e);else if("compressor"===c)d=new self.je(b,...e);else if("analyser"===c)d=new self.ie(b,...e);else throw Error("invalid effect type");g=b;h=k;h=h.toLowerCase();let l=g.ja.get(h);l||(l=[],g.ja.set(h,l));d.Rd=l.length;d.dd=
h;l.push(d);qb(g,h)}rb(b)}
async function sb(b,a){const c=a.saveLoadMode;if(3!==c){var d=[];for(var e of b.H)e.Aa()&&1===c||!e.Aa()&&2===c?d.push(e):e.j();b.H=d}for(const f of b.ja.values())for(const g of f)g.j();b.ja.clear();b.mc=a.timeScale;b.Oc=a.gameTime;d=a.listenerPos;b.$[0]=d[0];b.$[1]=d[1];b.$[2]=d[2];b.g.listener.setPosition(d[0],d[1],d[2]);d=a.listenerOrientation;if(Array.isArray(d)){for(e=0;6>e;++e)b.ca[e]=d[e];b.g.listener.setOrientation(...b.ca)}b.va=a.isSilent;b.m.Ob(b.va);b.bc=a.masterVolume;b.Ta.gain.value=
b.bc;d=[];for(const f of Object.values(a.effects))d.push(Promise.all(f.map(g=>pb(b,g))));await Promise.all(d);await Promise.all(a.playing.map(f=>tb(b,f,c)));S(b)}
async function ub(b,a){try{const c=b.g.suspend(a.time);b.Qd?b.g.resume():(b.g.startRendering().then(d=>{const e=[];for(let f=0,g=d.numberOfChannels;f<g;++f){const h=d.getChannelData(f);e.push(h.buffer)}b.m.ob("runtime","offline-audio-render-completed",{duration:d.duration,length:d.length,numberOfChannels:d.numberOfChannels,sampleRate:d.sampleRate,channelData:e},null,e)}).catch(d=>yb(d)),b.Qd=!0);await c}catch(c){yb(c)}}
function cb(b){b.Wb||(b.Qc=!1,window.addEventListener("pointerup",b.ya,!0),window.addEventListener("touchend",b.ya,!0),window.addEventListener("click",b.ya,!0),window.addEventListener("keydown",b.ya,!0),b.Wb=!0)}
async function O(b,a,c,d,e,f){for(var g of b.ia)if(g.kb()===c)return await zb(g),g;if(f)return null;if(e&&(b.hc||b.Pd)){f=0;for(let h=0,k=b.ia.length;h<k;++h)g=b.ia[h],b.ia[f]=g,g.Aa()?g.j():++f;b.ia.length=f}f="audio/webm; codecs=opus"===d&&!b.de;e&&f&&(b.Pd=!0);c=!e||b.hc||f?new self.we(b,a,c,d,e,f):new self.ue(b,a,c,d,e);b.ia.push(c);await zb(c);b.Wd.has(a)||(m(b,"buffer-metadata",{originalUrl:a,duration:c.fa()}),b.Wd.add(a));return c}
function Ab(b,a){return b===a||b.normalize().toLowerCase()===a.normalize().toLowerCase()}function Bb(b,a){return(a=b.ja.get(a.toLowerCase()))?a[0].N():b.ea()}function qb(b,a){a=a.toLowerCase();let c=b.ea();var d=b.ja.get(a);if(d&&d.length){c=d[0].N();for(let f=0,g=d.length;f<g;++f){var e=d[f];f+1===g?e.U(b.ea()):e.U(d[f+1].N())}}for(const f of Cb(b,a))e=f,d=c,e=e.da||e.F||e.G,e.disconnect(),e.connect(d);b.Ha&&b.Xc===a&&(b.Ha.disconnect(),b.Ha.connect(c))}
function*Cb(b,a){if(a)for(const c of b.H)Ab(0<c.na.length?c.na[0]:"",a)&&(yield c);else b.R&&!b.R.O()&&(yield b.R)}function Db(b,a,c){return c?b.m.ef(a).then(d=>{const e=b.g.createBuffer(1,d.length,48E3);e.getChannelData(0).set(d);return e}):new Promise((d,e)=>{b.g.decodeAudioData(a,d,e)})}function Eb(b,a){let c=0;for(let d=0,e=b.H.length;d<e;++d){const f=b.H[d];b.H[c]=f;f.P===a?f.j():++c}b.H.length=c}
function*R(b,a){if(0<a.length)for(const d of b.H){a:{b=d.na;var c=a;for(const e of c){c=!1;for(const f of b)if(Ab(f,e)){c=!0;break}if(!c){b=!1;break a}}b=!0}b&&(yield d)}else b.R&&!b.R.O()&&(yield b.R)}async function fb(b,a,c,d,e,f){for(const g of b.H)if(g.kb()===c&&(g.qc()||f))return g.na=e,g;a=await O(b,a,c,d,f);e="html5"===a.Kc?new self.ve(a.u,a,e):new self.xe(a.u,a,e);b.H.push(e);return e}
function eb(b,a){a=a.join(" ");let c=b.Fb.get(a);if(!c){let d=null;c={kd:0,promise:new Promise(e=>d=e),resolve:d};b.Fb.set(a,c)}c.kd++}function kb(b,a){return(b=b.Fb.get((0===a.length?b.Ud:a).join(" ")))?b.promise:Promise.resolve()}function S(b){if(0<b.Sa.size)w(b);else for(const a of b.H)if(!a.I&&!a.O()){w(b);break}}function Fb(b,a,c,d){m(b,"trigger",{type:a,tags:c,aiid:d})}function rb(b){b.Uc||(b.Uc=!0,Promise.resolve().then(()=>Gb(b)))}
function Gb(b){const a={};for(const [c,d]of b.ja)a[c]=d.map(e=>e.jb());m(b,"fxstate",{fxstate:a});b.Uc=!1}
async function tb(b,a,c){if(3!==c){var d=a.bufferOriginalUrl,e=a.bufferUrl,f=a.bufferType,g=a.isMusic,h=a.tags,k=a.isLooping,l=a.volume,p=a.playbackTime;if(!g||1!==c)if(g||2!==c){c=null;try{c=await fb(b,d,e,f,h,g)}catch(r){console.error("[Construct] Audio: error loading audio state: ",r);return}b=c;(d=a.pan)?(P(b,!0),e=b.F,f=d.pos,b.$a[0]=f[0],b.$a[1]=f[1],b.$a[2]=f[2],f=d.orient,b.Za[0]=f[0],b.Za[1]=f[1],b.Za[2]=f[2],e.setPosition(...b.$a),e.setOrientation(...b.Za),b.ra[0]=d.cia,b.ra[1]=d.coa,b.ra[2]=
d.cog,e.coneInnerAngle=d.cia,e.coneOuterAngle=d.coa,e.coneOuterGain=d.cog,b.pa=d.uid):P(b,!1);b=c;d=a.stereoPan;"number"!==typeof d?Q(b,!1):(Q(b,!0),hb(b,d));c.Play(k,l,p,0);a.isPlaying||c.nb();c.Fc(a)}}}function yb(b){console.error("[Audio] Offline rendering error: ",b)}
self.ib=class extends self.La{constructor(b){super(b,"audio");this.Ta=this.g=null;this.Wb=this.Qc=!1;this.ya=()=>{if(!this.Qc){var a=this.g;"suspended"===a.state&&a.resume&&a.resume();var c=a.createBuffer(1,220,22050),d=a.createBufferSource();d.buffer=c;d.connect(a.destination);d.start(0);"running"===a.state&&this.Wb&&(this.Qc=!0,window.removeEventListener("pointerup",this.ya,!0),window.removeEventListener("touchend",this.ya,!0),window.removeEventListener("click",this.ya,!0),window.removeEventListener("keydown",
this.ya,!0),this.Wb=!1)}};this.ia=[];this.H=[];this.R=null;this.Ud=[];this.Wd=new Set;this.Vd=-1;this.Fb=new Map;this.bc=1;this.va=!1;this.fd=0;this.mc=1;this.Oc=0;this.Yd="HRTF";this.Id="inverse";this.Zd=600;this.Xd=1E4;this.ae=1;this.$=[0,0,0];this.ca=[0,0,-1,0,1,0];this.Pd=this.hc=!1;this.de=this.m.Ce();this.ja=new Map;this.Sa=new Set;this.Qd=this.Uc=!1;this.Xc="";this.Ha=null;self.C3Audio_OnMicrophoneStream=(a,c)=>{this.Ha&&this.Ha.disconnect();this.Xc=c.toLowerCase();this.Ha=this.g.createMediaStreamSource(a);
this.Ha.connect(Bb(this,this.Xc))};this.Ub=null;self.C3Audio_GetOutputStream=()=>{this.Ub||(this.Ub=this.g.createMediaStreamDestination(),this.Ta.connect(this.Ub));return this.Ub.stream};self.C3Audio_DOMInterface=this;v(this,[["create-audio-context",a=>bb(this,a)],["play",a=>db(this,a)],["stop",a=>{a=a.tags;for(const c of R(this,a))c.Ba()}],["stop-all",()=>{for(const a of this.H)a.Ba()}],["set-paused",a=>{const c=a.tags;a=a.paused;for(const d of R(this,c))a?d.nb():d.Nb();S(this)}],["set-volume",a=>
{const c=a.tags;a=a.vol;for(const d of R(this,c))T(d,a)}],["fade-volume",a=>jb(this,a)],["set-master-volume",a=>{this.bc=a.vol;this.Ta.gain.value=this.bc}],["set-muted",a=>{const c=a.tags;a=a.isMuted;for(const d of R(this,c))Hb(d,a)}],["set-silent",a=>{this.va=a.isSilent;this.m.Ob(this.va);for(const c of this.H)c.Sb()}],["set-looping",a=>{const c=a.tags;a=a.isLooping;for(const d of R(this,c))d.yc(a)}],["set-playback-rate",a=>lb(this,a)],["set-stereo-pan",a=>{const c=a.tags;a=a.p;for(const d of R(this,
c))Q(d,!0),hb(d,a)}],["seek",a=>mb(this,a)],["preload",a=>nb(this,a)],["unload",a=>ob(this,a)],["unload-all",()=>{for(const a of this.ia)a.j();this.ia.length=0}],["set-suspended",a=>{a=a.isSuspended;!a&&this.g.resume&&this.g.resume();for(const c of this.H)c.zc(a);a&&this.g.suspend&&this.g.suspend()}],["add-effect",a=>pb(this,a)],["set-effect-param",a=>{var c=a.tags;const d=a.index,e=a.param,f=a.value,g=a.ramp;a=a.time;for(const h of c)c=this.ja.get(h.toLowerCase()),!c||0>d||d>=c.length||c[d].Z(e,
f,g,a);rb(this)}],["remove-effects",a=>{a=a.tags;for(const c of a){a=c.toLowerCase();const d=this.ja.get(a);if(!d||!d.length)break;for(const e of d)e.j();this.ja.delete(a);qb(this,a)}}],["tick",a=>{this.mc=a.timeScale;this.Oc=a.gameTime;this.Vd=a.tickCount;if(0!==this.fd)for(var c of this.H)c.Da();!(c=a.listenerPos)||this.$[0]===c[0]&&this.$[1]===c[1]&&this.$[2]===c[2]||(this.$[0]=c[0],this.$[1]=c[1],this.$[2]=c[2],this.g.listener.setPosition(c[0],c[1],c[2]));if((c=a.listenerOrientation)&&(this.ca[0]!==
c[0]||this.ca[1]!==c[1]||this.ca[2]!==c[2]||this.ca[3]!==c[3]||this.ca[4]!==c[4]||this.ca[5]!==c[5])){for(let d=0;6>d;++d)this.ca[d]=c[d];this.g.listener.setOrientation(...this.ca)}for(const d of a.instPans){a=d.uid;for(const e of this.H)e.pa===a&&gb(e,d.x,d.y,d.z,d.angle)}}],["load-state",a=>sb(this,a)],["offline-render-audio",a=>ub(this,a)],["offline-render-finish",()=>{this.g.resume()}]])}V(){return this.g}ea(){return this.Ta}GetAudioContextExtern(){return this.V()}GetDestinationNodeExtern(){return this.ea()}Mb(){return this.va}Ca(b){this.m.Ca(b)}Oa(b){this.m.Oa(b)}Qa(){for(var b of this.Sa)b.Qa();
b=this.g.currentTime;for(var a of this.H)a.Qa(b);a=this.H.filter(c=>!c.I&&!c.O()).map(c=>c.jb());m(this,"state",{tickCount:this.Vd,outputLatency:this.g.outputLatency||0,audioInstances:a,analysers:[...this.Sa].map(c=>({tag:c.dd,index:c.Rd,peak:c.ab,rms:c.$d,binCount:c.l.frequencyBinCount,freqBins:c.Nd}))});0===a.length&&0===this.Sa.size&&this.Xb&&(this.m.Bd(this.ee),this.Xb=!1)}static He(b){return b*ab}static qd(b){return Math.max(Math.min(Math.pow(10,b/20),1),0)}static Fe(b){return Math.log(Math.max(Math.min(b,
1),0))/Math.log(10)*20}};self.Pa.hb(self.ib);"use strict";function zb(b){b.$b||(b.$b=b.Ec());return b.$b}self.md=class{constructor(b,a,c,d,e){this.u=b;this.lf=a;this.Ja=c;this.T=d;this.gf=e;this.Kc="";this.$b=null}j(){this.$b=this.u=null}Ec(){}V(){return this.u.V()}uc(){return this.lf}kb(){return this.Ja}sc(){return this.T}Aa(){return this.gf}fa(){}};"use strict";
self.ue=class extends self.md{constructor(b,a,c,d,e){super(b,a,c,d,e);this.Kc="html5";this.L=new Audio;this.L.crossOrigin="anonymous";this.L.autoplay=!1;this.L.preload="auto";this.Ab=this.Bb=null;this.L.addEventListener("canplaythrough",()=>!0);this.Eb=this.V().createGain();this.Db=null;this.L.addEventListener("canplay",()=>{this.Bb&&(this.Bb(),this.Ab=this.Bb=null);!this.Db&&this.L&&(this.Db=this.V().createMediaElementSource(this.L),this.Db.connect(this.Eb))});this.onended=null;this.L.addEventListener("ended",
()=>{if(this.onended)this.onended()});this.L.addEventListener("error",f=>{console.error(`[Construct] Audio '${this.Ja}' error: `,f);this.Ab&&(this.Ab(f),this.Ab=this.Bb=null)})}j(){Eb(this.u,this);this.Eb.disconnect();this.Eb=null;this.Db.disconnect();this.Db=null;this.L&&!this.L.paused&&this.L.pause();this.L=this.onended=null;super.j()}Ec(){return new Promise((b,a)=>{this.Bb=b;this.Ab=a;this.L.src=this.Ja})}W(){return this.L}fa(){return this.L.duration}};"use strict";
async function Ib(b){if(b.Fa)return b.Fa;var a=b.u.m;if("cordova"===a.A&&a.td(b.Ja)&&a.Yb)b.Fa=await a.Kb(b.Ja);else{a=await fetch(b.Ja);if(!a.ok)throw Error(`error fetching audio data: ${a.status} ${a.statusText}`);b.Fa=await a.arrayBuffer()}}async function Jb(b){if(b.ha)return b.ha;b.ha=await Db(b.u,b.Fa,b.kf);b.Fa=null}
self.we=class extends self.md{constructor(b,a,c,d,e,f){super(b,a,c,d,e);this.Kc="webaudio";this.ha=this.Fa=null;this.kf=!!f}j(){Eb(this.u,this);this.ha=this.Fa=null;super.j()}async Ec(){try{await Ib(this),await Jb(this)}catch(b){console.error(`[Construct] Failed to load audio '${this.Ja}': `,b)}}fa(){return this.ha?this.ha.duration:0}};"use strict";let Kb=0;
function P(b,a){a=!!a;b.xb!==a&&(b.xb=a,b.xb?(Q(b,!1),b.F||(b.F=b.V().createPanner(),b.F.panningModel=b.u.Yd,b.F.distanceModel=b.u.Id,b.F.refDistance=b.u.Zd,b.F.maxDistance=b.u.Xd,b.F.rolloffFactor=b.u.ae),b.G.disconnect(),b.G.connect(b.F),b.F.connect(b.ea())):(b.F.disconnect(),b.G.disconnect(),b.G.connect(b.ea())))}
function Q(b,a){a=!!a;b.Zb!==a&&(b.Zb=a,b.Zb?(P(b,!1),b.da=b.V().createStereoPanner(),b.G.disconnect(),b.G.connect(b.da),b.da.connect(b.ea())):(b.da.disconnect(),b.da=null,b.G.disconnect(),b.G.connect(b.ea())))}function hb(b,a){b.Zb&&b.cd!==a&&(b.da.pan.value=a,b.cd=a)}function T(b,a){b.Ka=a;b.G.gain.cancelScheduledValues(0);b.Wa=-1;b.G.gain.value=b.vc()}function Hb(b,a){a=!!a;b.ua!==a&&(b.ua=a,b.Sb())}
function gb(b,a,c,d,e){if(b.xb){var f=b.$a,g=b.Za,h=Math.cos(e);e=Math.sin(e);if(f[0]!==a||f[1]!==c||f[2]!==d)f[0]=a,f[1]=c,f[2]=d,b.F.setPosition(...f);if(g[0]!==h||g[1]!==e||0!==g[2])g[0]=h,g[1]=e,g[2]=0,b.F.setOrientation(...g)}}function U(b){return b.Vc?b.u.Oc:performance.now()/1E3}
self.nd=class{constructor(b,a,c){this.u=b;this.P=a;this.na=c;this.Tb=Kb++;this.G=this.V().createGain();this.G.connect(this.ea());this.F=null;this.xb=!1;this.$a=[0,0,0];this.Za=[0,0,0];this.ra=[0,0,0];this.da=null;this.Zb=!1;this.cd=0;this.I=!0;this.Y=this.sa=this.J=!1;this.Ka=1;this.ua=!1;this.la=1;b=this.u.fd;this.Vc=1===b&&!this.Aa()||2===b;this.Wa=this.pa=-1;this.ce=!1}j(){this.P=this.u=null;this.F&&(this.F.disconnect(),this.F=null);this.da&&(this.da.disconnect(),this.da=null);this.G.disconnect();
this.G=null}V(){return this.u.V()}ea(){return Bb(this.u,0<this.na.length?this.na[0]:"")}uc(){return this.P.uc()}kb(){return this.P.kb()}sc(){return this.P.sc()}Aa(){return this.P.Aa()}O(){}qc(){}IsPlaying(){return!this.I&&!this.J&&!this.O()}Ma(){}fa(){return this.P.fa()}Play(){}Ba(){}nb(){}Nb(){}Qa(b){-1!==this.Wa&&b>=this.Wa&&(this.Wa=-1,this.ce&&this.Ba(),Fb(this.u,"fade-ended",this.na,this.Tb))}vc(){const b=this.Ka;return isFinite(b)?b:0}Mb(){return this.u.Mb()}Sb(){}yc(){}Da(){}xc(){}zc(){}wc(){}jb(){var b=
this.Tb,a=this.na,c=this.fa(),d=-1===this.Wa?this.Ka:this.G.gain.value,e=this.IsPlaying();if(this.F){var f=this.F;f={pos:this.$a,orient:this.Za,cia:f.coneInnerAngle,coa:f.coneOuterAngle,cog:f.coneOuterGain,uid:this.pa}}else f=null;return{aiid:b,tags:a,duration:c,volume:d,isPlaying:e,playbackTime:this.Ma(),playbackRate:this.la,uid:this.pa,bufferOriginalUrl:this.uc(),bufferUrl:"",bufferType:this.sc(),isMusic:this.Aa(),isLooping:this.Y,isMuted:this.ua,resumePosition:this.wc(),pan:f,stereoPan:this.da?
this.cd:null}}Fc(b){var a=b.playbackRate;this.la!==a&&(this.la=a,this.Da());Hb(this,b.isMuted)}};"use strict";
self.ve=class extends self.nd{constructor(b,a,c){super(b,a,c);this.P.Eb.connect(this.G);this.P.onended=()=>this.Gc()}j(){this.Ba();this.P.Eb.disconnect();super.j()}W(){return this.P.W()}Gc(){this.I=!0;this.pa=-1;Fb(this.u,"ended",this.na,this.Tb)}O(){return this.W().ended}qc(){return this.I?!0:this.O()}Ma(){let b=this.W().currentTime;this.Y||(b=Math.min(b,this.fa()));return b}Play(b,a,c){const d=this.W();1!==d.playbackRate&&(d.playbackRate=1);d.loop!==b&&(d.loop=b);T(this,a);this.ua=!1;d.muted&&(d.muted=
!1);if(d.currentTime!==c)try{d.currentTime=c}catch(e){console.warn(`[Construct] Exception seeking audio '${this.P.kb()}' to position '${c}': `,e)}this.u.Ca(d);this.J=this.I=!1;this.Y=b;this.la=1}Ba(){const b=this.W();b.paused||b.pause();this.u.Oa(b);this.I=!0;this.J=!1;this.pa=-1}nb(){if(!(this.J||this.I||this.O())){var b=this.W();b.paused||b.pause();this.u.Oa(b);this.J=!0}}Nb(){!this.J||this.I||this.O()||(this.u.Ca(this.W()),this.J=!1)}Sb(){this.W().muted=this.ua||this.Mb()}yc(b){b=!!b;this.Y!==
b&&(this.Y=b,this.W().loop=b)}Da(){let b=this.la;this.Vc&&(b*=this.u.mc);try{this.W().playbackRate=b}catch(a){console.warn(`[Construct] Unable to set playback rate '${b}':`,a)}}xc(b){if(!this.I&&!this.O())try{this.W().currentTime=b}catch(a){console.warn(`[Construct] Error seeking audio to '${b}': `,a)}}wc(){return this.Ma()}zc(b){b?this.IsPlaying()?(this.W().pause(),this.sa=!0):this.sa=!1:this.sa&&(this.u.Ca(this.W()),this.sa=!1)}};"use strict";
function V(b){b.s&&(b.s.onended=null,b.s.disconnect(),b.s.buffer=null);b.s=null;b.qb=null}
self.xe=class extends self.nd{constructor(b,a,c){super(b,a,c);this.s=null;this.dc=d=>this.Gc(d);this.Pc=!0;this.qb=null;this.S=this.fc=this.ic=0;this.Zc=1}j(){this.Ba();V(this);this.dc=null;super.j()}Gc(b){this.J||this.sa||b.target!==this.qb||(this.I=this.Pc=!0,this.pa=-1,V(this),Fb(this.u,"ended",this.na,this.Tb))}O(){return!this.I&&this.s&&this.s.loop||this.J?!1:this.Pc}qc(){return!this.s||this.I?!0:this.O()}Ma(){let b;b=this.J?this.S:this.fc+(U(this)-this.ic)*this.la;this.Y||(b=Math.min(b,this.fa()));
return b}Play(b,a,c,d){this.ua=!1;this.Zc=1;T(this,a);V(this);this.s=this.V().createBufferSource();this.s.buffer=this.P.ha;this.s.connect(this.G);this.qb=this.s;this.s.onended=this.dc;this.s.loop=b;this.s.start(d,c);this.J=this.I=this.Pc=!1;this.Y=b;this.la=1;this.ic=U(this);this.fc=c}Ba(){if(this.s)try{this.s.stop(0)}catch(b){}this.I=!0;this.J=!1;this.pa=-1}nb(){this.J||this.I||this.O()||(this.S=this.Ma(),this.Y&&(this.S%=this.fa()),this.J=!0,this.s.stop(0))}Nb(){!this.J||this.I||this.O()||(V(this),
this.s=this.V().createBufferSource(),this.s.buffer=this.P.ha,this.s.connect(this.G),this.qb=this.s,this.s.onended=this.dc,this.s.loop=this.Y,T(this,this.Ka),this.Da(),this.s.start(0,this.S),this.ic=U(this),this.fc=this.S,this.J=!1)}vc(){return super.vc()*this.Zc}Sb(){this.Zc=this.ua||this.Mb()?0:1;T(this,this.Ka)}yc(b){b=!!b;this.Y!==b&&(this.Y=b,this.s&&(this.s.loop=b))}Da(){let b=this.la;this.Vc&&(b*=this.u.mc);this.s&&(this.s.playbackRate.value=b)}xc(b){this.I||this.O()||(this.J?this.S=b:(this.nb(),
this.S=b,this.Nb()))}wc(){return this.S}zc(b){b?this.IsPlaying()?(this.sa=!0,this.S=this.Ma(),this.Y&&(this.S%=this.fa()),this.s.stop(0)):this.sa=!1:this.sa&&(V(this),this.s=this.V().createBufferSource(),this.s.buffer=this.P.ha,this.s.connect(this.G),this.qb=this.s,this.s.onended=this.dc,this.s.loop=this.Y,T(this,this.Ka),this.Da(),this.s.start(0,this.S),this.ic=U(this),this.fc=this.S,this.sa=!1)}Fc(b){super.Fc(b);this.S=b.resumePosition}};"use strict";function W(b){return b.g.createGain()}
function X(b,a,c,d,e){a.cancelScheduledValues(0);if(0===e)a.value=c;else switch(b=b.g.currentTime,e+=b,d){case 0:a.setValueAtTime(c,e);break;case 1:a.setValueAtTime(a.value,b);a.linearRampToValueAtTime(c,e);break;case 2:a.setValueAtTime(a.value,b),a.exponentialRampToValueAtTime(c,e)}}class Y{constructor(b){this.u=b;this.g=b.V();this.Rd=-1;this.T=this.dd="";this.o=null}j(){this.g=null}N(){}U(){}jb(){return{type:this.T,tag:this.dd,params:this.o}}}
self.ne=class extends Y{constructor(b,a,c,d,e,f,g){super(b);this.T="filter";this.o=[a,c,d,e,f,g];this.v=W(this);this.i=W(this);this.i.gain.value=g;this.h=W(this);this.h.gain.value=1-g;this.D=this.g.createBiquadFilter();this.D.type=a;this.D.frequency.value=c;this.D.detune.value=d;this.D.Q.value=e;this.D.gain.vlaue=f;this.v.connect(this.D);this.v.connect(this.h);this.D.connect(this.i)}j(){this.v.disconnect();this.D.disconnect();this.i.disconnect();this.h.disconnect();super.j()}U(b){this.i.disconnect();
this.i.connect(b);this.h.disconnect();this.h.connect(b)}N(){return this.v}Z(b,a,c,d){switch(b){case 0:a=Math.max(Math.min(a/100,1),0);this.o[5]=a;X(this,this.i.gain,a,c,d);X(this,this.h.gain,1-a,c,d);break;case 1:this.o[1]=a;X(this,this.D.frequency,a,c,d);break;case 2:this.o[2]=a;X(this,this.D.detune,a,c,d);break;case 3:this.o[3]=a;X(this,this.D.Q,a,c,d);break;case 4:this.o[4]=a,X(this,this.D.gain,a,c,d)}}};
self.le=class extends Y{constructor(b,a,c,d){super(b);this.T="delay";this.o=[a,c,d];this.v=W(this);this.i=W(this);this.i.gain.value=d;this.h=W(this);this.h.gain.value=1-d;this.Cb=W(this);this.X=this.g.createDelay(a);this.X.delayTime.value=a;this.vb=W(this);this.vb.gain.value=c;this.v.connect(this.Cb);this.v.connect(this.h);this.Cb.connect(this.i);this.Cb.connect(this.X);this.X.connect(this.vb);this.vb.connect(this.Cb)}j(){this.v.disconnect();this.i.disconnect();this.h.disconnect();this.Cb.disconnect();
this.X.disconnect();this.vb.disconnect();super.j()}U(b){this.i.disconnect();this.i.connect(b);this.h.disconnect();this.h.connect(b)}N(){return this.v}Z(b,a,c,d){const e=self.ib.qd;switch(b){case 0:a=Math.max(Math.min(a/100,1),0);this.o[2]=a;X(this,this.i.gain,a,c,d);X(this,this.h.gain,1-a,c,d);break;case 4:this.o[1]=e(a);X(this,this.vb.gain,e(a),c,d);break;case 5:this.o[0]=a,X(this,this.X.delayTime,a,c,d)}}};
self.ke=class extends Y{constructor(b,a,c,d){super(b);this.T="convolution";this.o=[c,d];this.Hd=this.Gd="";this.v=W(this);this.i=W(this);this.i.gain.value=d;this.h=W(this);this.h.gain.value=1-d;this.ub=this.g.createConvolver();this.ub.normalize=c;this.ub.buffer=a;this.v.connect(this.ub);this.v.connect(this.h);this.ub.connect(this.i)}j(){this.v.disconnect();this.ub.disconnect();this.i.disconnect();this.h.disconnect();super.j()}U(b){this.i.disconnect();this.i.connect(b);this.h.disconnect();this.h.connect(b)}N(){return this.v}Z(b,
a,c,d){switch(b){case 0:a=Math.max(Math.min(a/100,1),0),this.o[1]=a,X(this,this.i.gain,a,c,d),X(this,this.h.gain,1-a,c,d)}}jb(){const b=super.jb();b.bufferOriginalUrl=this.Gd;b.bufferUrl="";b.bufferType=this.Hd;return b}};
self.oe=class extends Y{constructor(b,a,c,d,e,f){super(b);this.T="flanger";this.o=[a,c,d,e,f];this.v=W(this);this.h=W(this);this.h.gain.value=1-f/2;this.i=W(this);this.i.gain.value=f/2;this.wb=W(this);this.wb.gain.value=e;this.X=this.g.createDelay(a+c);this.X.delayTime.value=a;this.C=this.g.createOscillator();this.C.frequency.value=d;this.K=W(this);this.K.gain.value=c;this.v.connect(this.X);this.v.connect(this.h);this.X.connect(this.i);this.X.connect(this.wb);this.wb.connect(this.X);this.C.connect(this.K);
this.K.connect(this.X.delayTime);this.C.start(0)}j(){this.C.stop(0);this.v.disconnect();this.X.disconnect();this.C.disconnect();this.K.disconnect();this.h.disconnect();this.i.disconnect();this.wb.disconnect();super.j()}U(b){this.i.disconnect();this.i.connect(b);this.h.disconnect();this.h.connect(b)}N(){return this.v}Z(b,a,c,d){switch(b){case 0:a=Math.max(Math.min(a/100,1),0);this.o[4]=a;X(this,this.i.gain,a/2,c,d);X(this,this.h.gain,1-a/2,c,d);break;case 6:this.o[1]=a/1E3;X(this,this.K.gain,a/1E3,
c,d);break;case 7:this.o[2]=a;X(this,this.C.frequency,a,c,d);break;case 8:this.o[3]=a/100,X(this,this.wb.gain,a/100,c,d)}}};
self.qe=class extends Y{constructor(b,a,c,d,e,f,g){super(b);this.T="phaser";this.o=[a,c,d,e,f,g];this.v=W(this);this.h=W(this);this.h.gain.value=1-g/2;this.i=W(this);this.i.gain.value=g/2;this.D=this.g.createBiquadFilter();this.D.type="allpass";this.D.frequency.value=a;this.D.detune.value=c;this.D.Q.value=d;this.C=this.g.createOscillator();this.C.frequency.value=f;this.K=W(this);this.K.gain.value=e;this.v.connect(this.D);this.v.connect(this.h);this.D.connect(this.i);this.C.connect(this.K);this.K.connect(this.D.frequency);
this.C.start(0)}j(){this.C.stop(0);this.v.disconnect();this.D.disconnect();this.C.disconnect();this.K.disconnect();this.h.disconnect();this.i.disconnect();super.j()}U(b){this.i.disconnect();this.i.connect(b);this.h.disconnect();this.h.connect(b)}N(){return this.v}Z(b,a,c,d){switch(b){case 0:a=Math.max(Math.min(a/100,1),0);this.o[5]=a;X(this,this.i.gain,a/2,c,d);X(this,this.h.gain,1-a/2,c,d);break;case 1:this.o[0]=a;X(this,this.D.frequency,a,c,d);break;case 2:this.o[1]=a;X(this,this.D.detune,a,c,d);
break;case 3:this.o[2]=a;X(this,this.D.Q,a,c,d);break;case 6:this.o[3]=a;X(this,this.K.gain,a,c,d);break;case 7:this.o[4]=a,X(this,this.C.frequency,a,c,d)}}};self.pe=class extends Y{constructor(b,a){super(b);this.T="gain";this.o=[a];this.l=W(this);this.l.gain.value=a}j(){this.l.disconnect();super.j()}U(b){this.l.disconnect();this.l.connect(b)}N(){return this.l}Z(b,a,c,d){const e=self.ib.qd;switch(b){case 4:this.o[0]=e(a),X(this,this.l.gain,e(a),c,d)}}};
self.se=class extends Y{constructor(b,a){super(b);this.T="stereopan";this.o=[a];this.l=this.g.createStereoPanner();this.l.pan.value=a}j(){this.l.disconnect();super.j()}U(b){this.l.disconnect();this.l.connect(b)}N(){return this.l}Z(b,a,c,d){a=Math.min(Math.max(a/100,-1),1);switch(b){case 9:this.o[0]=a,X(this,this.l.pan,a,c,d)}}};
self.te=class extends Y{constructor(b,a,c){super(b);this.T="tremolo";this.o=[a,c];this.l=W(this);this.l.gain.value=1-c/2;this.C=this.g.createOscillator();this.C.frequency.value=a;this.K=W(this);this.K.gain.value=c/2;this.C.connect(this.K);this.K.connect(this.l.gain);this.C.start(0)}j(){this.C.stop(0);this.C.disconnect();this.K.disconnect();this.l.disconnect();super.j()}U(b){this.l.disconnect();this.l.connect(b)}N(){return this.l}Z(b,a,c,d){switch(b){case 0:a=Math.max(Math.min(a/100,1),0);this.o[1]=
a;X(this,this.l.gain,1-a/2,c,d);X(this,this.K.gain,a/2,c,d);break;case 7:this.o[0]=a,X(this,this.C.frequency,a,c,d)}}};
self.re=class extends Y{constructor(b,a,c){super(b);this.T="ringmod";this.o=[a,c];this.v=W(this);this.i=W(this);this.i.gain.value=c;this.h=W(this);this.h.gain.value=1-c;this.Hb=W(this);this.Hb.gain.value=0;this.C=this.g.createOscillator();this.C.frequency.value=a;this.C.connect(this.Hb.gain);this.C.start(0);this.v.connect(this.Hb);this.v.connect(this.h);this.Hb.connect(this.i)}j(){this.C.stop(0);this.C.disconnect();this.Hb.disconnect();this.v.disconnect();this.i.disconnect();this.h.disconnect();super.j()}U(b){this.i.disconnect();
this.i.connect(b);this.h.disconnect();this.h.connect(b)}N(){return this.v}Z(b,a,c,d){switch(b){case 0:a=Math.max(Math.min(a/100,1),0);this.o[1]=a;X(this,this.i.gain,a,c,d);X(this,this.h.gain,1-a,c,d);break;case 7:this.o[0]=a,X(this,this.C.frequency,a,c,d)}}};
self.me=class extends Y{constructor(b,a,c,d,e,f){super(b);this.T="distortion";this.o=[a,c,d,e,f];this.v=W(this);this.kc=W(this);this.jc=W(this);b=d;.01>b&&(b=.01);this.kc.gain.value=b;this.jc.gain.value=Math.pow(1/b,.6)*e;this.i=W(this);this.i.gain.value=f;this.h=W(this);this.h.gain.value=1-f;this.nc=this.g.createWaveShaper();this.Lc=new Float32Array(65536);for(e=0;32768>e;++e)f=e/32768,b=1.05*c*a-a,d=0>f?-f:f,d<a?b=d:(d=1-Math.exp(-(1/b)*(d-a)),b=a+b*d),f=b*(0>f?-1:1),this.Lc[32768+e]=f,this.Lc[32768-
e-1]=-f;this.nc.curve=this.Lc;this.v.connect(this.kc);this.v.connect(this.h);this.kc.connect(this.nc);this.nc.connect(this.jc);this.jc.connect(this.i)}j(){this.v.disconnect();this.kc.disconnect();this.nc.disconnect();this.jc.disconnect();this.i.disconnect();this.h.disconnect();super.j()}U(b){this.i.disconnect();this.i.connect(b);this.h.disconnect();this.h.connect(b)}N(){return this.v}Z(b,a,c,d){switch(b){case 0:a=Math.max(Math.min(a/100,1),0),this.o[4]=a,X(this,this.i.gain,a,c,d),X(this,this.h.gain,
1-a,c,d)}}};self.je=class extends Y{constructor(b,a,c,d,e,f){super(b);this.T="compressor";this.o=[a,c,d,e,f];this.l=this.g.createDynamicsCompressor();this.l.threshold.value=a;this.l.knee.value=c;this.l.ratio.value=d;this.l.attack.value=e;this.l.release.value=f}j(){this.l.disconnect();super.j()}U(b){this.l.disconnect();this.l.connect(b)}N(){return this.l}Z(){}};
self.ie=class extends Y{constructor(b,a,c){super(b);this.T="analyser";this.o=[a,c];this.l=this.g.createAnalyser();this.l.fftSize=a;this.l.smoothingTimeConstant=c;this.Nd=new Float32Array(this.l.frequencyBinCount);this.be=new Uint8Array(a);this.$d=this.ab=0;b=this.u;b.Sa.add(this);S(b)}j(){this.u.Sa.delete(this);this.l.disconnect();super.j()}Qa(){this.l.getFloatFrequencyData(this.Nd);this.l.getByteTimeDomainData(this.be);const b=this.l.fftSize;let a=this.ab=0;for(var c=0;c<b;++c){let d=(this.be[c]-
128)/128;0>d&&(d=-d);this.ab<d&&(this.ab=d);a+=d*d}c=self.ib.Fe;this.ab=c(this.ab);this.$d=c(Math.sqrt(a/b))}U(b){this.l.disconnect();this.l.connect(b)}N(){return this.l}Z(){}};"use strict";async function Lb(){try{return{isOk:!0,isPersistent:await navigator.storage.persist()}}catch(b){return console.error("[Construct] Error requesting persistent storage: ",b),{isOk:!1}}}
self.Pa.hb(class extends self.La{constructor(b){super(b,"localstorage");v(this,[["init",()=>this.Pb()],["request-persistent",()=>Lb()]])}async Pb(){let b=!1;try{b=await navigator.storage.persisted()}catch(a){b=!1,console.warn("[Construct] Error checking storage persisted state: ",a)}return{isPersistent:b}}});"use strict";async function Mb(b,a){a=a.type;let c=!0;0===a?c=await Nb():1===a&&(c=await Ob());m(b,"permission-result",{type:a,result:c})}
async function Nb(){if(!self.DeviceOrientationEvent||!self.DeviceOrientationEvent.requestPermission)return!0;try{return"granted"===await self.DeviceOrientationEvent.requestPermission()}catch(b){return console.warn("[Touch] Failed to request orientation permission: ",b),!1}}
async function Ob(){if(!self.DeviceMotionEvent||!self.DeviceMotionEvent.requestPermission)return!0;try{return"granted"===await self.DeviceMotionEvent.requestPermission()}catch(b){return console.warn("[Touch] Failed to request motion permission: ",b),!1}}self.Pa.hb(class extends self.La{constructor(b){super(b,"touch");q(this,"request-permission",a=>Mb(this,a))}});"use strict";function Pb(b){return new Promise((a,c)=>{b.getInsetTop(a,c)})}
function Qb(b){return new Promise((a,c)=>{b.getInsetRight(a,c)})}function Rb(b){return new Promise((a,c)=>{b.getInsetBottom(a,c)})}function Sb(b){return new Promise((a,c)=>{b.getInsetLeft(a,c)})}async function Tb(){const b=await Ub();return{screenWidth:screen.width,screenHeight:screen.height,windowOuterWidth:window.outerWidth,windowOuterHeight:window.outerHeight,safeAreaInset:b,supportsWakeLock:!!navigator.wakeLock,isNwjs:"undefined"!==typeof nw}}
async function Vb(b){if(!b.Ia)try{b.Ia=await navigator.wakeLock.request("screen"),b.Ia.addEventListener("release",()=>{console.log("[Construct] Screen wake lock released");b.Ia=null;m(b,"wake-lock-released")}),console.log("[Construct] Screen wake lock acquired"),m(b,"wake-lock-acquired")}catch(a){console.warn("[Construct] Failed to acquire screen wake lock: ",a),m(b,"wake-lock-error")}}
async function Wb(b){const a=await Ub();m(b,"window-resize",{windowOuterWidth:window.outerWidth,windowOuterHeight:window.outerHeight,safeAreaInset:a})}
async function Ub(){var b=self.AndroidNotch;if(b)try{return await Promise.all([Pb(b),Qb(b),Rb(b),Sb(b)])}catch(c){return console.error("[Construct] Failed to get Android safe area inset: ",c),[0,0,0,0]}else{var a=document.body;b=a.style;b.setProperty("--temp-sai-top","env(safe-area-inset-top)");b.setProperty("--temp-sai-right","env(safe-area-inset-right)");b.setProperty("--temp-sai-bottom","env(safe-area-inset-bottom)");b.setProperty("--temp-sai-left","env(safe-area-inset-left)");a=getComputedStyle(a);
a=[a.getPropertyValue("--temp-sai-top"),a.getPropertyValue("--temp-sai-right"),a.getPropertyValue("--temp-sai-bottom"),a.getPropertyValue("--temp-sai-left")].map(c=>{c=parseInt(c,10);return isFinite(c)?c:0});b.removeProperty("--temp-sai-top");b.removeProperty("--temp-sai-right");b.removeProperty("--temp-sai-bottom");b.removeProperty("--temp-sai-left");return a}}
self.Pa.hb(class extends self.La{constructor(b){super(b,"platform-info");v(this,[["get-initial-state",()=>Tb()],["request-wake-lock",()=>Vb(this)],["release-wake-lock",()=>{this.Ia&&(this.Ia.release(),this.Ia=null)}]]);window.addEventListener("resize",()=>Wb(this));this.Ia=null}});
